services:
  - type: web
    name: tasued-biovault
    runtime: node
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /api/health
    buildCommand: DATABASE_URL=postgresql://placeholder:placeholder@localhost:5432/placeholder npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: "https://tasued-biometric-sys.onrender.com"
      - key: WEBAUTHN_RP_ID
        value: "tasued-biometric-sys.onrender.com"
      - key: WEBAUTHN_ORIGIN
        value: "https://tasued-biometric-sys.onrender.com"
      - key: BCRYPT_SALT_ROUNDS
        value: "12"
      - key: SECURE_COOKIES
        value: "true"
      - key: JWT_EXPIRES_IN
        value: "24h"
